#ifndef __POUS_H
#define __POUS_H

#include "accessor.h"
#include "iec_std_lib.h"

// PROGRAM SFC_PROGRAM
// Data part
typedef struct {
  // PROGRAM Interface - IN, OUT, IN_OUT variables

  // PROGRAM private variables - TEMP, private and located variables
  __DECLARE_VAR(BOOL,INIT_ACTIVE)
  __DECLARE_VAR(BOOL,VALIDATEINPUT_ACTIVE)
  __DECLARE_VAR(BOOL,VALIDATIONERROR_ACTIVE)
  __DECLARE_VAR(BOOL,CHECK_ACTIVE)
  __DECLARE_VAR(BOOL,ADD_ACTIVE)
  __DECLARE_VAR(BOOL,INC_ACTIVE)
  __DECLARE_VAR(BOOL,SAFEABORT_ACTIVE)
  __DECLARE_VAR(BOOL,END_ACTIVE)
  __DECLARE_VAR(BOOL,SAFETYCHECKINPUT_ACTIVE)
  __DECLARE_VAR(BOOL,SAFETYERROR_ACTIVE)
  __DECLARE_VAR(BOOL,SAFETYLOG_ACTIVE)
  __DECLARE_VAR(INT,TRI)
  __DECLARE_VAR(INT,I)
  __DECLARE_VAR(INT,N)
  __DECLARE_VAR(INT,INIT)
  __DECLARE_VAR(INT,LOOP_COUNT)
  __DECLARE_VAR(INT,MAX_N)
  __DECLARE_VAR(INT,MAX_ITERATIONS)

} SFC_PROGRAM;

void SFC_PROGRAM_init__(SFC_PROGRAM *data__, BOOL retain);
// Code part
void SFC_PROGRAM_body__(SFC_PROGRAM *data__);
#endif //__POUS_H
